---
version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    volumes:
      - "jenkins_home:/var/jenkins_home"

networks:
  default:
    external:
      name: dap

volumes:
  jenkins_home:
