---
version: '3.1'
services:
  db:
    image: mysql
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: 'Cyberark1'
